# Generated by Django 5.0.3 on 2024-04-08 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promt', models.CharField(max_length=100)),
                ('neg_promt', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('transparency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promt', models.CharField(max_length=100)),
                ('neg_promt', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('login', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('patronymic', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.background')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.logo')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.person')),
            ],
        ),
    ]
