# Generated by Django 5.0.3 on 2024-04-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='background',
            old_name='neg_promt',
            new_name='neg_prompt',
        ),
        migrations.RenameField(
            model_name='background',
            old_name='promt',
            new_name='prompt',
        ),
        migrations.RenameField(
            model_name='logo',
            old_name='neg_promt',
            new_name='neg_prompt',
        ),
        migrations.RenameField(
            model_name='logo',
            old_name='promt',
            new_name='prompt',
        ),
    ]
