# Generated by Django 5.0.3 on 2024-04-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_rename_neg_promt_background_neg_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='neg_prompt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='background',
            name='prompt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='logo',
            name='neg_prompt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='logo',
            name='prompt',
            field=models.TextField(),
        ),
    ]
