# Generated by Django 5.0.3 on 2024-04-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_background_neg_prompt_alter_background_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='neg_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='logo',
            name='neg_prompt',
            field=models.TextField(blank=True),
        ),
    ]
