# Generated by Django 5.0.3 on 2024-04-15 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_background_neg_prompt_alter_card_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='transparency',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
