# Generated by Django 5.0.3 on 2024-04-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_background_neg_prompt_alter_card_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='text_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
