# Generated by Django 5.0.3 on 2024-05-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_remove_card_patronymic_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='text_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
